import Head from 'next/head';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/router';
import { Inter } from 'next/font/google';
import { Header } from '@/shared/header/header';
import { SignInForm } from '@/components/auth-form/components/sign-in-form';
import routes from '@/utils/routes';
import styles from './index.module.scss';

const inter = Inter({ subsets: ['latin'] });

export const HomePage = () => {
  const router = useRouter();
  const { data } = useSession();

  if (data) router.push(routes.endpoints.profile);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={`${styles.main} ${inter.className}`}>
        <SignInForm />
      </main>
    </>
  );
};

export default HomePage;
