import Head from 'next/head';
import { Inter } from 'next/font/google';
import { SignInForm } from '@/components/auth-form/components/sign-in-form';
import styles from './home.module.scss';

const inter = Inter({ subsets: ['latin'] });

const HomePage = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={`${styles.main} ${inter.className}`}>
      <SignInForm />
    </main>
  </>
);

export default HomePage;
